local WaveCompressionType = { [1] = "Microsoft PCM", -- Hex Value: 0x1
                              [2] = "Microsoft ADPCM", -- Hex Value: 0x2
                              [3] = "Microsoft IEEE float", -- Hex Value: 0x3
                              [4] = "Compaq VSELP", -- Hex Value: 0x4
                              [5] = "IBM CVSD", -- Hex Value: 0x5
                              [6] = "Microsoft a-Law", -- Hex Value: 0x6
                              [7] = "Microsoft u-Law", -- Hex Value: 0x7
                              [8] = "Microsoft DTS", -- Hex Value: 0x8
                              [9] = "DRM", -- Hex Value: 0x9
                              [10] = "WMA 9 Speech", -- Hex Value: 0xa
                              [11] = "Microsoft Windows Media RT Voice", -- Hex Value: 0xb
                              [16] = "OKI-ADPCM", -- Hex Value: 0x10
                              [17] = "Intel IMA/DVI-ADPCM", -- Hex Value: 0x11
                              [18] = "Videologic Mediaspace ADPCM", -- Hex Value: 0x12
                              [19] = "Sierra ADPCM", -- Hex Value: 0x13
                              [20] = "Antex G.723 ADPCM", -- Hex Value: 0x14
                              [21] = "DSP Solutions DIGISTD", -- Hex Value: 0x15
                              [22] = "DSP Solutions DIGIFIX", -- Hex Value: 0x16
                              [23] = "Dialoic OKI ADPCM", -- Hex Value: 0x17
                              [24] = "Media Vision ADPCM", -- Hex Value: 0x18
                              [25] = "HP CU", -- Hex Value: 0x19
                              [26] = "HP Dynamic Voice", -- Hex Value: 0x1a
                              [32] = "Yamaha ADPCM", -- Hex Value: 0x20
                              [33] = "SONARC Speech Compression", -- Hex Value: 0x21
                              [34] = "DSP Group True Speech", -- Hex Value: 0x22
                              [35] = "Echo Speech Corp.", -- Hex Value: 0x23
                              [36] = "Virtual Music Audiofile AF36", -- Hex Value: 0x24
                              [37] = "Audio Processing Tech.", -- Hex Value: 0x25
                              [38] = "Virtual Music Audiofile AF10", -- Hex Value: 0x26
                              [39] = "Aculab Prosody 1612", -- Hex Value: 0x27
                              [40] = "Merging Tech. LRC", -- Hex Value: 0x28
                              [48] = "Dolby AC2", -- Hex Value: 0x30
                              [49] = "Microsoft GSM610", -- Hex Value: 0x31
                              [50] = "MSN Audio", -- Hex Value: 0x32
                              [51] = "Antex ADPCME", -- Hex Value: 0x33
                              [52] = "Control Resources VQLPC", -- Hex Value: 0x34
                              [53] = "DSP Solutions DIGIREAL", -- Hex Value: 0x35
                              [54] = "DSP Solutions DIGIADPCM", -- Hex Value: 0x36
                              [55] = "Control Resources CR10", -- Hex Value: 0x37
                              [56] = "Natural MicroSystems VBX ADPCM", -- Hex Value: 0x38
                              [57] = "Crystal Semiconductor IMA ADPCM", -- Hex Value: 0x39
                              [58] = "Echo Speech ECHOSC3", -- Hex Value: 0x3a
                              [59] = "Rockwell ADPCM", -- Hex Value: 0x3b
                              [60] = "Rockwell DIGITALK", -- Hex Value: 0x3c
                              [61] = "Xebec Multimedia", -- Hex Value: 0x3d
                              [64] = "Antex G.721 ADPCM", -- Hex Value: 0x40
                              [65] = "Antex G.728 CELP", -- Hex Value: 0x41
                              [66] = "Microsoft MSG723", -- Hex Value: 0x42
                              [67] = "IBM AVC ADPCM", -- Hex Value: 0x43
                              [69] = "ITU-T G.726", -- Hex Value: 0x45
                              [80] = "Microsoft MPEG", -- Hex Value: 0x50
                              [81] = "RT23 or PAC", -- Hex Value: 0x51
                              [82] = "InSoft RT24", -- Hex Value: 0x52
                              [83] = "InSoft PAC", -- Hex Value: 0x53
                              [85] = "MP3", -- Hex Value: 0x55
                              [89] = "Cirrus", -- Hex Value: 0x59
                              [96] = "Cirrus Logic", -- Hex Value: 0x60
                              [97] = "ESS Tech. PCM", -- Hex Value: 0x61
                              [98] = "Voxware Inc.", -- Hex Value: 0x62
                              [99] = "Canopus ATRAC", -- Hex Value: 0x63
                              [100] = "APICOM G.726 ADPCM", -- Hex Value: 0x64
                              [101] = "APICOM G.722 ADPCM", -- Hex Value: 0x65
                              [102] = "Microsoft DSAT", -- Hex Value: 0x66
                              [103] = "Micorsoft DSAT DISPLAY", -- Hex Value: 0x67
                              [105] = "Voxware Byte Aligned", -- Hex Value: 0x69
                              [112] = "Voxware AC8", -- Hex Value: 0x70
                              [113] = "Voxware AC10", -- Hex Value: 0x71
                              [114] = "Voxware AC16", -- Hex Value: 0x72
                              [115] = "Voxware AC20", -- Hex Value: 0x73
                              [116] = "Voxware MetaVoice", -- Hex Value: 0x74
                              [117] = "Voxware MetaSound", -- Hex Value: 0x75
                              [118] = "Voxware RT29HW", -- Hex Value: 0x76
                              [119] = "Voxware VR12", -- Hex Value: 0x77
                              [120] = "Voxware VR18", -- Hex Value: 0x78
                              [121] = "Voxware TQ40", -- Hex Value: 0x79
                              [122] = "Voxware SC3", -- Hex Value: 0x7a
                              [123] = "Voxware SC3", -- Hex Value: 0x7b
                              [128] = "Soundsoft", -- Hex Value: 0x80
                              [129] = "Voxware TQ60", -- Hex Value: 0x81
                              [130] = "Microsoft MSRT24", -- Hex Value: 0x82
                              [131] = "AT&T G.729A", -- Hex Value: 0x83
                              [132] = "Motion Pixels MVI MV12", -- Hex Value: 0x84
                              [133] = "DataFusion G.726", -- Hex Value: 0x85
                              [134] = "DataFusion GSM610", -- Hex Value: 0x86
                              [136] = "Iterated Systems Audio", -- Hex Value: 0x88
                              [137] = "Onlive", -- Hex Value: 0x89
                              [138] = "Multitude, Inc. FT SX20", -- Hex Value: 0x8a
                              [139] = "Infocom ITS A/S G.721 ADPCM", -- Hex Value: 0x8b
                              [140] = "Convedia G729", -- Hex Value: 0x8c
                              [141] = "Not specified congruency, Inc.", -- Hex Value: 0x8d
                              [145] = "Siemens SBC24", -- Hex Value: 0x91
                              [146] = "Sonic Foundry Dolby AC3 APDIF", -- Hex Value: 0x92
                              [147] = "MediaSonic G.723", -- Hex Value: 0x93
                              [148] = "Aculab Prosody 8kbps", -- Hex Value: 0x94
                              [151] = "ZyXEL ADPCM", -- Hex Value: 0x97
                              [152] = "Philips LPCBB", -- Hex Value: 0x98
                              [153] = "Studer Professional Audio Packed", -- Hex Value: 0x99
                              [160] = "Malden PhonyTalk", -- Hex Value: 0xa0
                              [161] = "Racal Recorder GSM", -- Hex Value: 0xa1
                              [162] = "Racal Recorder G720.a", -- Hex Value: 0xa2
                              [163] = "Racal G723.1", -- Hex Value: 0xa3
                              [164] = "Racal Tetra ACELP", -- Hex Value: 0xa4
                              [176] = "NEC AAC NEC Corporation", -- Hex Value: 0xb0
                              [255] = "AAC", -- Hex Value: 0xff
                              [256] = "Rhetorex ADPCM", -- Hex Value: 0x100
                              [257] = "IBM u-Law", -- Hex Value: 0x101
                              [258] = "IBM a-Law", -- Hex Value: 0x102
                              [259] = "IBM ADPCM", -- Hex Value: 0x103
                              [273] = "Vivo G.723", -- Hex Value: 0x111
                              [274] = "Vivo Siren", -- Hex Value: 0x112
                              [288] = "Philips Speech Processing CELP", -- Hex Value: 0x120
                              [289] = "Philips Speech Processing GRUNDIG", -- Hex Value: 0x121
                              [291] = "Digital G.723", -- Hex Value: 0x123
                              [293] = "Sanyo LD ADPCM", -- Hex Value: 0x125
                              [304] = "Sipro Lab ACEPLNET", -- Hex Value: 0x130
                              [305] = "Sipro Lab ACELP4800", -- Hex Value: 0x131
                              [306] = "Sipro Lab ACELP8V3", -- Hex Value: 0x132
                              [307] = "Sipro Lab G.729", -- Hex Value: 0x133
                              [308] = "Sipro Lab G.729A", -- Hex Value: 0x134
                              [309] = "Sipro Lab Kelvin", -- Hex Value: 0x135
                              [310] = "VoiceAge AMR", -- Hex Value: 0x136
                              [320] = "Dictaphone G.726 ADPCM", -- Hex Value: 0x140
                              [336] = "Qualcomm PureVoice", -- Hex Value: 0x150
                              [337] = "Qualcomm HalfRate", -- Hex Value: 0x151
                              [341] = "Ring Zero Systems TUBGSM", -- Hex Value: 0x155
                              [352] = "Microsoft Audio1", -- Hex Value: 0x160
                              [353] = "Windows Media Audio V2 V7 V8 V9 / DivX audio (WMA) / Alex AC3 Audio", -- Hex Value: 0x161
                              [354] = "Windows Media Audio Professional V9", -- Hex Value: 0x162
                              [355] = "Windows Media Audio Lossless V9", -- Hex Value: 0x163
                              [356] = "WMA Pro over S/PDIF", -- Hex Value: 0x164
                              [357] = "XMA1 (XBox 360)",
                              [358] = "XMA2 (XBox 360)",
                              [368] = "UNISYS NAP ADPCM", -- Hex Value: 0x170
                              [369] = "UNISYS NAP ULAW", -- Hex Value: 0x171
                              [370] = "UNISYS NAP ALAW", -- Hex Value: 0x172
                              [371] = "UNISYS NAP 16K", -- Hex Value: 0x173
                              [372] = "MM SYCOM ACM SYC008 SyCom Technologies", -- Hex Value: 0x174
                              [373] = "MM SYCOM ACM SYC701 G726L SyCom Technologies", -- Hex Value: 0x175
                              [374] = "MM SYCOM ACM SYC701 CELP54 SyCom Technologies", -- Hex Value: 0x176
                              [375] = "MM SYCOM ACM SYC701 CELP68 SyCom Technologies", -- Hex Value: 0x177
                              [376] = "Knowledge Adventure ADPCM", -- Hex Value: 0x178
                              [384] = "Fraunhofer IIS MPEG2AAC", -- Hex Value: 0x180
                              [400] = "Digital Theater Systems DTS DS", -- Hex Value: 0x190
                              [512] = "Creative Labs ADPCM", -- Hex Value: 0x200
                              [514] = "Creative Labs FASTSPEECH8", -- Hex Value: 0x202
                              [515] = "Creative Labs FASTSPEECH10", -- Hex Value: 0x203
                              [528] = "UHER ADPCM", -- Hex Value: 0x210
                              [533] = "Ulead DV ACM", -- Hex Value: 0x215
                              [534] = "Ulead DV ACM", -- Hex Value: 0x216
                              [544] = "Quarterdeck Corp.", -- Hex Value: 0x220
                              [560] = "I-Link VC", -- Hex Value: 0x230
                              [576] = "Aureal Semiconductor Raw Sport", -- Hex Value: 0x240
                              [577] = "ESST AC3", -- Hex Value: 0x241
                              [592] = "Interactive Products HSX", -- Hex Value: 0x250
                              [593] = "Interactive Products RPELP", -- Hex Value: 0x251
                              [608] = "Consistent CS2", -- Hex Value: 0x260
                              [624] = "Sony SCX", -- Hex Value: 0x270
                              [625] = "Sony SCY", -- Hex Value: 0x271
                              [626] = "Sony ATRAC3", -- Hex Value: 0x272
                              [627] = "Sony SPC", -- Hex Value: 0x273
                              [640] = "TELUM Telum Inc.", -- Hex Value: 0x280
                              [641] = "TELUMIA Telum Inc.", -- Hex Value: 0x281
                              [645] = "Norcom Voice Systems ADPCM", -- Hex Value: 0x285
                              [768] = "Fujitsu FM TOWNS SND", -- Hex Value: 0x300
                              [769] = "Fujitsu (not specified)", -- Hex Value: 0x301
                              [770] = "Fujitsu (not specified)", -- Hex Value: 0x302
                              [771] = "Fujitsu (not specified)", -- Hex Value: 0x303
                              [772] = "Fujitsu (not specified)", -- Hex Value: 0x304
                              [773] = "Fujitsu (not specified)", -- Hex Value: 0x305
                              [774] = "Fujitsu (not specified)", -- Hex Value: 0x306
                              [775] = "Fujitsu (not specified)", -- Hex Value: 0x307
                              [776] = "Fujitsu (not specified)", -- Hex Value: 0x308
                              [848] = "Micronas Semiconductors, Inc. Development", -- Hex Value: 0x350
                              [849] = "Micronas Semiconductors, Inc. CELP833", -- Hex Value: 0x351
                              [1024] = "Brooktree Digital", -- Hex Value: 0x400
                              [1025] = "Intel Music Coder (IMC)", -- Hex Value: 0x401
                              [1026] = "Ligos Indeo Audio", -- Hex Value: 0x402
                              [1104] = "QDesign Music", -- Hex Value: 0x450
                              [1280] = "On2 VP7 On2 Technologies", -- Hex Value: 0x500
                              [1281] = "On2 VP6 On2 Technologies", -- Hex Value: 0x501
                              [1664] = "AT&T VME VMPCM", -- Hex Value: 0x680
                              [1665] = "AT&T TCP", -- Hex Value: 0x681
                              [1792] = "YMPEG Alpha (dummy for MPEG-2 compressor)", -- Hex Value: 0x700
                              [2222] = "ClearJump LiteWave (lossless)", -- Hex Value: 0x8ae
                              [4096] = "Olivetti GSM", -- Hex Value: 0x1000
                              [4097] = "Olivetti ADPCM", -- Hex Value: 0x1001
                              [4098] = "Olivetti CELP", -- Hex Value: 0x1002
                              [4099] = "Olivetti SBC", -- Hex Value: 0x1003
                              [4100] = "Olivetti OPR", -- Hex Value: 0x1004
                              [4352] = "Lernout & Hauspie", -- Hex Value: 0x1100
                              [4353] = "Lernout & Hauspie CELP codec", -- Hex Value: 0x1101
                              [4354] = "Lernout & Hauspie SBC codec", -- Hex Value: 0x1102
                              [4355] = "Lernout & Hauspie SBC codec", -- Hex Value: 0x1103
                              [4356] = "Lernout & Hauspie SBC codec", -- Hex Value: 0x1104
                              [5120] = "Norris Comm. Inc.", -- Hex Value: 0x1400
                              [5121] = "ISIAudio", -- Hex Value: 0x1401
                              [5376] = "AT&T Soundspace Music Compression", -- Hex Value: 0x1500
                              [6172] = "VoxWare RT24 speech codec", -- Hex Value: 0x181c
                              [6174] = "Lucent elemedia AX24000P Music codec", -- Hex Value: 0x181e
                              [6513] = "Sonic Foundry LOSSLESS", -- Hex Value: 0x1971
                              [6521] = "Innings Telecom Inc. ADPCM", -- Hex Value: 0x1979
                              [7175] = "Lucent SX8300P speech codec", -- Hex Value: 0x1c07
                              [7180] = "Lucent SX5363S G.723 compliant codec", -- Hex Value: 0x1c0c
                              [7939] = "CUseeMe DigiTalk (ex-Rocwell)", -- Hex Value: 0x1f03
                              [8132] = "NCT Soft ALF2CD ACM", -- Hex Value: 0x1fc4
                              [8192] = "FAST Multimedia DVM", -- Hex Value: 0x2000
                              [8193] = "Dolby DTS (Digital Theater System)", -- Hex Value: 0x2001
                              [8194] = "RealAudio 1 / 2 14.4", -- Hex Value: 0x2002
                              [8195] = "RealAudio 1 / 2 28.8", -- Hex Value: 0x2003
                              [8196] = "RealAudio G2 / 8 Cook (low bitrate)", -- Hex Value: 0x2004
                              [8197] = "RealAudio 3 / 4 / 5 Music (DNET)", -- Hex Value: 0x2005
                              [8198] = "RealAudio 10 AAC (RAAC)", -- Hex Value: 0x2006
                              [8199] = "RealAudio 10 AAC+ (RACP)", -- Hex Value: 0x2007
                              [9472] = "Reserved range to 0x2600 Microsoft", -- Hex Value: 0x2500
                              [13075] = "makeAVIS (ffvfw fake AVI sound from AviSynth scripts)", -- Hex Value: 0x3313
                              [16707] = "Divio MPEG-4 AAC audio", -- Hex Value: 0x4143
                              [16897] = "Nokia adaptive multirate", -- Hex Value: 0x4201
                              [16963] = "Divio G726 Divio, Inc.", -- Hex Value: 0x4243
                              [17228] = "LEAD Speech", -- Hex Value: 0x434c
                              [22092] = "LEAD Vorbis", -- Hex Value: 0x564c
                              [22358] = "WavPack Audio", -- Hex Value: 0x5756
                              [26447] = "Ogg Vorbis (mode 1)", -- Hex Value: 0x674f
                              [26448] = "Ogg Vorbis (mode 2)", -- Hex Value: 0x6750
                              [26449] = "Ogg Vorbis (mode 3)", -- Hex Value: 0x6751
                              [26479] = "Ogg Vorbis (mode 1+)", -- Hex Value: 0x676f
                              [26480] = "Ogg Vorbis (mode 2+)", -- Hex Value: 0x6770
                              [26481] = "Ogg Vorbis (mode 3+)", -- Hex Value: 0x6771
                              [28672] = "3COM NBX 3Com Corporation", -- Hex Value: 0x7000
                              [28781] = "FAAD AAC", -- Hex Value: 0x706d
                              [31265] = "GSM-AMR (CBR, no SID)", -- Hex Value: 0x7a21
                              [31266] = "GSM-AMR (VBR, including SID)", -- Hex Value: 0x7a22
                              [41216] = "Comverse Infosys Ltd. G723 1", -- Hex Value: 0xa100
                              [41217] = "Comverse Infosys Ltd. AVQSBC", -- Hex Value: 0xa101
                              [41218] = "Comverse Infosys Ltd. OLDSBC", -- Hex Value: 0xa102
                              [41219] = "Symbol Technologies G729A", -- Hex Value: 0xa103
                              [41220] = "VoiceAge AMR WB VoiceAge Corporation", -- Hex Value: 0xa104
                              [41221] = "Ingenient Technologies Inc. G726", -- Hex Value: 0xa105
                              [41222] = "ISO/MPEG-4 advanced audio Coding", -- Hex Value: 0xa106
                              [41223] = "Encore Software Ltd G726", -- Hex Value: 0xa107
                              [41225] = "Speex ACM Codec xiph.org", -- Hex Value: 0xa109
                              [57260] = "DebugMode SonicFoundry Vegas FrameServer ACM Codec", -- Hex Value: 0xdfac
                              [59144] = "Unknown -", -- Hex Value: 0xe708
                              [61868] = "Free Lossless Audio Codec FLAC", -- Hex Value: 0xf1ac
                              [65534] = "Extensible", -- Hex Value: 0xfffe
                              [65535] = "Development " } -- Hex Value: 0xffff 

return WaveCompressionType